version: '3'
services:
  redis:
    image: "redis:4.0.1-alpine"
  postgres:
    image: "postgres:9.6.5-alpine"
    environment:
     POSTGRES_PASSWORD: 123456
     POSTGRES_USER: postgres
  web:
    build: .
    ports:
     - "80:7777"
    volumes:
     - .:/usr/src/app
    depends_on:
      - postgres
      - redis
    command: ["./wait_for_it.sh", "postgres:5432", "--", "npm", "start"]