version: '3'
services:
  web:
    container_name: web
    build: .
    env_file: .env
    command: nodemon --inspect=5858 index.js
    volumes:
      -  .:/code
    ports:
      - "9100:9100"
      - "5858:5858"
    depends_on:
      - postgres
      - redis
    links:
      - "postgres:postgres"
      - "redis:redis"

  postgres:
    container_name: db
    image: postgres:10.0
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: buser
      POSTGRES_PASSWORD: buserpass
      POSTGRES_DB: bootcamp

  redis:
      container_name: redis
      image: redis:alpine
      ports:
        - "6379:6379"
